### ISSUE TITLE
Missing security Practices

### ISSUE THREAD

**Issue by Blake-Whitham** [JacobWPeterson/PostgresOnEC2#2]
- When mentioning CHMOD - you should warn about security issues and link to a best-practices page, as chmod is a very powerful command and can lead to complete compromise of your instance.
- For Security groups - 0.0.0.0::0 opens the IP to any origin, which can be good for trouble shooting. please reference [vpc peering](https://docs.aws.amazon.com/vpc/latest/peering/create-vpc-peering-connection.html) for added security measures.
- Reinforce that the PEM key should not be kept in the repo as there are bots combing for these in commit histories, and forgetting to .gitignore is a common occurrence.

**Comment by JacobWPeterson** [comment]
Thanks, @Blake-Whitham. I've added additional notes and references in these places and elsewhere.
